spring:
    application:
        name: hls-server
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    jackson:
        time-zone: Asia/Ho_Chi_Minh
        default-property-inclusion: non_null

server:
    port: 8080

app:
    jwt:
        signerKey: HDKdDVDEpABtpunTzN2QM2pbmVzDP5jht6WGykegNKgsKDVdDlbzFVmU1vDOVOHV
    hls:
        storage-path: C:\hls\data

logging:
    level:
        root: INFO
        com.rin: DEBUG