spring:
  application:
    name: load-balancer

  jackson:
    time-zone: UTC
    default-property-inclusion: non_null
  
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.rin.loadbalancer: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
